custom_config.settings_form:
  path: '/admin/config/custom/settings'
  defaults:
    _form: '\Drupal\custom_config\Form\Emailsending'
    _title: 'SettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE